import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/user/AuthContext";
import { Provider } from "@/components/ui/provider"
import { ChakraProvider } from "@chakra-ui/react";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import { AosInit } from "./_components/aos/aos-init";



const geistSans = Roboto({
  weight: ["400", "900"],
  subsets:["latin"]
});
const font = localFont({
  src: "./fonts/Roboto-VariableFont_wdth,wght.ttf",
  variable: "--font-Roboto-VariableFont",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased`}
      >

        <AuthProvider>
          {children}
          <AosInit/>
        </AuthProvider>

      </body>
    </html>
  );
}
